apiVersion: apps/v1
kind: deployment
metadata:
  name: helloworld-deployment
  namespace: development
spec:
  replicas: 4
  selector:
    matchlabel:
      app: helloworld
  template:
    metadata:
      labels:
        app: hello-world
  spec:
    terminationGracePeriodSeconds: 30
    containers:
    - name: hello-world
      image: anurag4516/helloworld:latest
      imagePullPolicy: "Always"
      ports:
      - containerPort: 80 



