apiVersion: v1
kind: Service
metadata:
  name: hello world service
  labels:
    name: hello-world
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 8080
      
  selector:
    name: hello-world